strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016' # windows-2019

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2 # we need it because we target netcoreapp2.0
  displayName: Install .NET Core 2.2 SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.402'
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet
- bash: ./build.sh
  condition: or( eq( variables['Agent.OS'], 'Darwin' ), eq( variables['Agent.OS'], 'Linux' ))
  displayName: 'build.sh'
- powershell: .\build.cmd
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'build.cmd'